name: nikolapeja6 Hello World

on:
  push:
    branches:
      - users/nikolapeja6/automation
  pull_request:
    branches:
      - users/nikolapeja6/automation

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
    steps:
      - name: Call GitHub Model API
        uses: actions/ai-inference@v1
        with:
          model: gpt-4o-mini
          system-prompt: "you are a helpful assistant"
          prompt: "describe github in two short sentances"
          github-token: ${{ secrets.GITHUB_TOKEN }}
